services:
  upload-service:
    build:
      context: .   # Build context is the root to allow copying common root files (settings.gradle)
      dockerfile: ./upload-service/Dockerfile
    container_name: upload-service
    ports:
      - "8081:8081" # Map host port 8081 to container port 8081
    volumes:
      - ${STORAGE_LOCATION}:/app/data
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - STORAGE_LOCATION=/app/data
    restart: unless-stopped
